export const brotherInfo = [
    {
        "id": 1.0,
        "name": "Richard Staebler",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/richardstaebler.jpg"
    },
    {
        "id": 2.0,
        "name": "Jonathan Wong",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/jonathanwong.jpg"
    },
    {
        "id": 3.0,
        "name": "Sarah Leung",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/sarahleung.jpg"
    },
    {
        "id": 4.0,
        "name": "Jacqueline Kim",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/jacquelinekim.jpg"
    },
    {
        "id": 5.0,
        "name": "Terence Leung",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/terenceleung.jpg"
    },
    {
        "id": 6.0,
        "name": "Jonathan Turcios",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/jonathanturcios.jpg"
    },
    {
        "id": 7.0,
        "name": "Amy Nguyen",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Earth System Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/amynguyen.jpg"
    },
    {
        "id": 8.0,
        "name": "Jeffrey Go",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/jeffreygo.jpg"
    },
    {
        "id": 9.0,
        "name": "Christopher Louie",
        "class": "Founding",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Founders/christopherlouie.jpg"
    },
    {
        "id": 10.0,
        "name": "Charles Chiang ",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/charleschiang.jpg"
    },
    {
        "id": 11.0,
        "name": "Walter Hsieh",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/walterhsieh.jpg"
    },
    {
        "id": 12.0,
        "name": "Elliot Huang",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/elliothuang.jpg"
    },
    {
        "id": 13.0,
        "name": "Bryan Le ",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/bryanle.jpg"
    },
    {
        "id": 14.0,
        "name": "Michelle Mueller",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/michellemueller.jpg"
    },
    {
        "id": 15.0,
        "name": "Nazneen Pashutanizadeh",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/nazneenpashutanizadeh.jpg"
    },
    {
        "id": 16.0,
        "name": "Siddharthan Selvasekar",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/siddharthanselvasekar.jpg"
    },
    {
        "id": 17.0,
        "name": "Patrick Sy ",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/patricksy.jpg"
    },
    {
        "id": 18.0,
        "name": "Chynna Velasco",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/chynnavelasco.jpg"
    },
    {
        "id": 19.0,
        "name": "Matthew Vera",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/mattvera.jpg"
    },
    {
        "id": 20.0,
        "name": "Eric Wengert ",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/ericwengert.jpg"
    },
    {
        "id": 21.0,
        "name": "Jack Zhai",
        "class": "Alpha",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Environmental Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Alpha/jackzhai.jpg"
    },
    {
        "id": 22.0,
        "name": "Gabrielle Abdon",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/gabrielleabdon.jpg"
    },
    {
        "id": 23.0,
        "name": "Evan Coombs ",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/evancoombs.jpg"
    },
    {
        "id": 24.0,
        "name": "Benjamin Halbach",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/benjaminhalbach.jpg"
    },
    {
        "id": 25.0,
        "name": "Kevin Huynh",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/kevinhuynh.jpg"
    },
    {
        "id": 26.0,
        "name": "Kelly Inciong",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/kellyinciong.jpg"
    },
    {
        "id": 27.0,
        "name": "Shan Kim",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/shankim.jpg"
    },
    {
        "id": 28.0,
        "name": "Andrew Kin",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/andrewkin.jpg"
    },
    {
        "id": 29.0,
        "name": "Eddie Kwan",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/eddiekwan.jpg"
    },
    {
        "id": 30.0,
        "name": "Allison Ramirez",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/allisonramirez.jpg"
    },
    {
        "id": 31.0,
        "name": "Laraib Saeed ",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mathmatics",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/laraibsaeed.jpg"
    },
    {
        "id": 32.0,
        "name": "Ya Thao",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/yathao.jpg"
    },
    {
        "id": 33.0,
        "name": "Andrew Toledo",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/andrewtoledo.jpg"
    },
    {
        "id": 34.0,
        "name": "Dustin Vo",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Environmental Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/dustinvo.jpg"
    },
    {
        "id": 35.0,
        "name": "Jasper Wang",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/jasperwang.jpg"
    },
    {
        "id": 36.0,
        "name": "Yijiao (Jo) Wang",
        "class": "Beta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Beta/yijaowang.jpg"
    },
    {
        "id": 37.0,
        "name": "Divya Bajaj",
        "class": "Gamma",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Gamma/divyabajaj.jpg"
    },
    {
        "id": 38.0,
        "name": "Casey Carter ",
        "class": "Gamma",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Gamma/caseycarter.jpg"
    },
    {
        "id": 39.0,
        "name": "Jessica Kao",
        "class": "Gamma",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Gamma/jessicakao.jpg"
    },
    {
        "id": 40.0,
        "name": "Nicolas Kurtz",
        "class": "Gamma",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Gamma/nicholaskurtz.jpg"
    },
    {
        "id": 41.0,
        "name": "Amelia Meyer",
        "class": "Gamma",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Gamma/ameliameyer.jpg"
    },
    {
        "id": 42.0,
        "name": "Connie Phan",
        "class": "Gamma",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Gamma/conniephan.jpg"
    },
    {
        "id": 43.0,
        "name": "Ashley Robinson",
        "class": "Gamma",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Gamma/ashleyrobinson.jpg"
    },
    {
        "id": 44.0,
        "name": "Martin Boyd",
        "class": "Delta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Delta/martinboyd.jpg"
    },
    {
        "id": 45.0,
        "name": "Yonathan Esquivel",
        "class": "Delta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Delta/yonathanesquivel.jpg"
    },
    {
        "id": 46.0,
        "name": "Brian Mugg",
        "class": "Delta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Delta/brianmugg.jpg"
    },
    {
        "id": 47.0,
        "name": "Adiseshu Peesapati",
        "class": "Delta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Delta/adiseshupeesapati.jpg"
    },
    {
        "id": 48.0,
        "name": "Chris Prijic",
        "class": "Delta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Delta/chrisprijic.jpg"
    },
    {
        "id": 49.0,
        "name": "Irvin Vazquez ",
        "class": "Delta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Delta/irvinvasquez.jpg"
    },
    {
        "id": 50.0,
        "name": "Telena Vo ",
        "class": "Delta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Environmental Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Delta/telenavo.jpg"
    },
    {
        "id": 51.0,
        "name": "Darren Yang ",
        "class": "Delta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Delta/darrenyang.jpg"
    },
    {
        "id": 52.0,
        "name": "Juan Contreras",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/juancontreras.jpg"
    },
    {
        "id": 53.0,
        "name": "Lynn Dannan",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/lynndannan.jpg"
    },
    {
        "id": 54.0,
        "name": "Anthony Foley",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/anthonyfoley.jpg"
    },
    {
        "id": 55.0,
        "name": "Daniel Klebe",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/danielklebe.jpg"
    },
    {
        "id": 56.0,
        "name": "Alex LaVelle",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/alexlavelle.jpg"
    },
    {
        "id": 57.0,
        "name": "Bryce Loop",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/byrceloop.jpg"
    },
    {
        "id": 58.0,
        "name": "Rio Menchaca",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/riomenchaca.jpg"
    },
    {
        "id": 59.0,
        "name": "Colleen Muawad",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemistry",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/colleenmuawad.jpg"
    },
    {
        "id": 60.0,
        "name": "Milan Odedra",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/milanodedra.jpg"
    },
    {
        "id": 61.0,
        "name": "Brian Seng",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/brianseng.jpg"
    },
    {
        "id": 62.0,
        "name": "Narumi Takagi",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/narumitakagi.jpg"
    },
    {
        "id": 63.0,
        "name": "Kush Thukral",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/kushthukral.jpg"
    },
    {
        "id": 64.0,
        "name": "Linda Ton",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Environmental Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/lindaton.jpg"
    },
    {
        "id": 65.0,
        "name": "Yen Tu",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/yentu.jpg"
    },
    {
        "id": 66.0,
        "name": "Chelsea Yuen",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/chelseayuen.jpg"
    },
    {
        "id": 67.0,
        "name": "Han Zheng",
        "class": "Epsilon",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Epsilon/hanzheng.jpg"
    },
    {
        "id": 68.0,
        "name": "Brandon Chen",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/brandonchen.jpg"
    },
    {
        "id": 69.0,
        "name": "Xavier Chuck",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/xavierchuck.jpg"
    },
    {
        "id": 70.0,
        "name": "Itzetl Frausto",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/itzetlfrausto.jpg"
    },
    {
        "id": 71.0,
        "name": "Ryan Hai",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/ryanhai.jpg"
    },
    {
        "id": 72.0,
        "name": "Winnie Hu",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/winniehu.jpg"
    },
    {
        "id": 73.0,
        "name": "Ryan Kawahara",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/ryankawahara.jpg"
    },
    {
        "id": 74.0,
        "name": "Christine Lao ",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/christinelao.jpg"
    },
    {
        "id": 75.0,
        "name": "Bryan Luong",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/bryanloung.jpg"
    },
    {
        "id": 76.0,
        "name": "Meghan Matibag",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/meghanmatibag.jpg"
    },
    {
        "id": 77.0,
        "name": "Mae Tamayo ",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/maetamayo.jpg"
    },
    {
        "id": 78.0,
        "name": "Anita Tran",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/anitatran.jpg"
    },
    {
        "id": 79.0,
        "name": "James Yi ",
        "class": "Zeta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Zeta/jamesyi.jpg"
    },
    {
        "id": 80.0,
        "name": "Jayvee Aspa",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/jayveeaspa.jpg"
    },
    {
        "id": 81.0,
        "name": "Sandy Dao",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/sandydao.jpg"
    },
    {
        "id": 82.0,
        "name": "Vivian Hang",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/vivianhuang.jpg"
    },
    {
        "id": 83.0,
        "name": "William Hsueh",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Materical Science Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/williamhsueh.jpg"
    },
    {
        "id": 84.0,
        "name": "Jevons Jiang",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/jevonsjiang.jpg"
    },
    {
        "id": 85.0,
        "name": "Jodie Loo",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/jodieloo.jpg"
    },
    {
        "id": 86.0,
        "name": "David Pham",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/davidpham.jpg"
    },
    {
        "id": 87.0,
        "name": "Weiqiang (Jesse) Yin",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Undeclared Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/weiqing(jessie)yin.jpg"
    },
    {
        "id": 88.0,
        "name": "Celina Chen",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering & Economics",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/celinachen.jpg"
    },
    {
        "id": 89.0,
        "name": "Cesar Ramales",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemcial Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/cesarramales.jpg"
    },
    {
        "id": 90.0,
        "name": "Amanda Reth",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Environmental Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/amandareth.jpg"
    },
    {
        "id": 91.0,
        "name": "Brittany Tran",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Environmental Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/brittanytran.jpg"
    },
    {
        "id": 92.0,
        "name": "Michelle (Ana) Tulean",
        "class": "Eta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Eta/michelle(ana)tulean.jpg"
    },
    {
        "id": 93.0,
        "name": "Rodney Buzon",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Materical Science Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/rodneybuzon.jpg"
    },
    {
        "id": 94.0,
        "name": "Baldwin Chang",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/baldwinchang.jpg"
    },
    {
        "id": 95.0,
        "name": "Samantha Huang",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/samanthahuang.jpg"
    },
    {
        "id": 96.0,
        "name": "Jackie Li ",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/jackieli.jpg"
    },
    {
        "id": 97.0,
        "name": "GuanYu Liu",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/guanyuliu.jpg"
    },
    {
        "id": 98.0,
        "name": "Andrew Melendez",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/andrewmelendez.jpg"
    },
    {
        "id": 99.0,
        "name": "Eric Nguyen",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/ericnguyen.jpg"
    },
    {
        "id": 100.0,
        "name": "Marlen Rojas ",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/marlenrojas.jpg"
    },
    {
        "id": 101.0,
        "name": "David Tran",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/davidtran.jpg"
    },
    {
        "id": 102.0,
        "name": "Derek Yeh ",
        "class": "Theta",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Theta/derekyeh.jpg"
    },
    {
        "id": 103.0,
        "name": "Michael Acasio",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/michaelacasio.jpg"
    },
    {
        "id": 104.0,
        "name": "Bridget Ventura",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/bridgetventura.jpg"
    },
    {
        "id": 105.0,
        "name": "Tina Chan",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Materical Science Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/tinachan.jpg"
    },
    {
        "id": 106.0,
        "name": "Allen Chang",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/allenchang.jpg"
    },
    {
        "id": 107.0,
        "name": "Daniel Duong",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/danielduong.jpg"
    },
    {
        "id": 108.0,
        "name": "Dean Gonzales",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/deangonzales.jpg"
    },
    {
        "id": 109.0,
        "name": "Dale Lee",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/dalelee.jpg"
    },
    {
        "id": 110.0,
        "name": "Sean Chih Wei Lee",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/seanchihweilee.jpg"
    },
    {
        "id": 111.0,
        "name": "Sergio Linares",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/sergiolinares.jpg"
    },
    {
        "id": 112.0,
        "name": "Vishal Mandalia",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/vishalmandalia.jpg"
    },
    {
        "id": 113.0,
        "name": "Dan Tang ",
        "class": "Iota",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Iota/dantang.jpg"
    },
    {
        "id": 114.0,
        "name": "Santiago Barrera",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/santiagobarrera.jpg"
    },
    {
        "id": 115.0,
        "name": "Heejun Chough",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Material Science Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/heejunchough.jpg"
    },
    {
        "id": 116.0,
        "name": "Jimmy Chung",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/jimmychung.jpg"
    },
    {
        "id": 117.0,
        "name": "Yun Jo (Kevin)",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/yunjo(kevin)chun.jpg"
    },
    {
        "id": 118.0,
        "name": "Henry Hoang",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/henryhoang.jpg"
    },
    {
        "id": 119.0,
        "name": "Joseph Hong",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/josephhong.jpg"
    },
    {
        "id": 120.0,
        "name": "Kyle Krumrei ",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/kylekrumrei.jpg"
    },
    {
        "id": 121.0,
        "name": "Jason Lee ",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/jasonlee.jpg"
    },
    {
        "id": 122.0,
        "name": "Keith Leung",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/keithleung.jpg"
    },
    {
        "id": 123.0,
        "name": "Kevin Nguyen",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/kevinnguyen.jpg"
    },
    {
        "id": 124.0,
        "name": "Leianne Roylo",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/leianneroylo.jpg"
    },
    {
        "id": 125.0,
        "name": "Brendon Tran",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/brendontran.jpg"
    },
    {
        "id": 126.0,
        "name": "Sophia Ynami ",
        "class": "Kappa",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Kappa/sophiaynami.jpg"
    },
    {
        "id": 127.0,
        "name": "Lawrence Chong",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/lawrencechong.jpg"
    },
    {
        "id": 128.0,
        "name": "Alvin Kwong",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/alvinkwong.jpg"
    },
    {
        "id": 129.0,
        "name": "Calvin Li",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Material Science Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/calvinli.jpg"
    },
    {
        "id": 130.0,
        "name": "Yu Wei Liu ",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/yuweiliu.jpg"
    },
    {
        "id": 131.0,
        "name": "John Luong",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/johnluong.jpg"
    },
    {
        "id": 132.0,
        "name": "Jessica Ma",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/jessicama.jpg"
    },
    {
        "id": 133.0,
        "name": "Laura Marsh",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Software Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/lauramarsh.jpg"
    },
    {
        "id": 134.0,
        "name": "Phi Nguyen",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/phinguyen.jpg"
    },
    {
        "id": 136.0,
        "name": "Nathan Padrid",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Software Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/nathanpadrid.jpg"
    },
    {
        "id": 137.0,
        "name": "Michael Pagdonsolan",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/michaelpagdonsolan.jpg"
    },
    {
        "id": 138.0,
        "name": "Aina Tancinco",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/ainatancinco.jpg"
    },
    {
        "id": 139.0,
        "name": "Viet Tran",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/viettran.jpg"
    },
    {
        "id": 140.0,
        "name": "Mandy Weng ",
        "class": "Lambda",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Lambda/mandyweng.jpg"
    },
    {
        "id": 141.0,
        "name": "Christopher Banh",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/christopherbanh.jpg"
    },
    {
        "id": 142.0,
        "name": "Steven Campos ",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/stevencampos.jpg"
    },
    {
        "id": 143.0,
        "name": "Jessica Chen",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/jessicachen.jpg"
    },
    {
        "id": 144.0,
        "name": "John Chua",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/johnchua.jpg"
    },
    {
        "id": 145.0,
        "name": "Brian Dang",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/briandang.jpg"
    },
    {
        "id": 146.0,
        "name": "Kevin Troy De Guzman",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/kevintroydeguzman.jpg"
    },
    {
        "id": 147.0,
        "name": "Sebastian Gao",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/sebastiangao.jpg"
    },
    {
        "id": 148.0,
        "name": "Tony Ho",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/tonyho.jpg"
    },
    {
        "id": 149.0,
        "name": "Agnes Jang",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/agnesjang.jpg"
    },
    {
        "id": 150.0,
        "name": "Tony Lao",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/tonylao.jpg"
    },
    {
        "id": 151.0,
        "name": "Theresa Le",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/theresale.jpg"
    },
    {
        "id": 152.0,
        "name": "Ruth Nguyen",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/ruthnguyen.jpg"
    },
    {
        "id": 153.0,
        "name": "Johnny Pham",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/johnnypham.jpg"
    },
    {
        "id": 154.0,
        "name": "Judith Rupasinghe",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/judithrupasinghe.jpg"
    },
    {
        "id": 155.0,
        "name": "Kayla San Pedro",
        "class": "Mu",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/kaylasanpedro.jpg"
    },
    {
        "id": 156.0,
        "name": "Michelle Vasquez ",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/michellecasquez.jpg"
    },
    {
        "id": 157.0,
        "name": "Kevin Wong",
        "class": "Mu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Mu/kevinwong.jpg"
    },
    {
        "id": 158.0,
        "name": "Chloe Agape",
        "class": "Nu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/chloeagape.jpg"
    },
    {
        "id": 159.0,
        "name": "Kevin Chen",
        "class": "Nu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/kevinchen.jpg"
    },
    {
        "id": 160.0,
        "name": "Willis Lao",
        "class": "Nu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/willislao.jpg"
    },
    {
        "id": 162.0,
        "name": "Dawn Malla",
        "class": "Nu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/dawnmalla.jpg"
    },
    {
        "id": 163.0,
        "name": "Shogo Nakamura ",
        "class": "Nu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/shogonakamura.jpg"
    },
    {
        "id": 164.0,
        "name": "Hailey Noe",
        "class": "Nu",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/haileynoe.jpg"
    },
    {
        "id": 165.0,
        "name": "Kyla Quilos",
        "class": "Nu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/kylaquilos.jpg"
    },
    {
        "id": 166.0,
        "name": "Jose Santillan",
        "class": "Nu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/josesantillan.jpg"
    },
    {
        "id": 167.0,
        "name": "Yvonne Szeto",
        "class": "Nu",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/yvonneszeto.jpg"
    },
    {
        "id": 168.0,
        "name": "Claire Xie",
        "class": "Nu",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/claire-xie-7a7b61148/",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Nu/clairexie.jpg"
    },
    {
        "id": 169.0,
        "name": "Karla Abad-Torrez",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/karlaabadtorrez.jpg"
    },
    {
        "id": 170.0,
        "name": "Maxine Apoderado",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/maxineapoderado.jpg"
    },
    {
        "id": 171.0,
        "name": "Eric Chen",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/ericchen.jpg"
    },
    {
        "id": 172.0,
        "name": "Paul John Evangelista (PJ) ",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/pauljohnevangelista.jpg"
    },
    {
        "id": 173.0,
        "name": "Sarah Huang",
        "class": "Xi",
        "active_status": "Y",
        "linkedin_url": "http://linkedin.com/in/sarah-huang-241520154",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/sarahhuang.jpg"
    },
    {
        "id": 174.0,
        "name": "Justin Huynh",
        "class": "Xi",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/justinhuynh.jpg"
    },
    {
        "id": 175.0,
        "name": "Jessica Lee",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/jessicalee.jpg"
    },
    {
        "id": 176.0,
        "name": "Lucy Liang",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/lucyliang.jpg"
    },
    {
        "id": 177.0,
        "name": "Amanda Lin",
        "class": "Xi",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/amandalin.jpg"
    },
    {
        "id": 178.0,
        "name": "Megan Nguyen",
        "class": "Xi",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/mwlite/in/dylan-kao-00299b163",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/megannguyen.jpg"
    },
    {
        "id": 179.0,
        "name": "Harry Pak",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/harrypak.jpg"
    },
    {
        "id": 180.0,
        "name": "Jason Tang ",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/jasontang.jpg"
    },
    {
        "id": 181.0,
        "name": "Hannad Trinh ",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/hannadtrinh.jpg"
    },
    {
        "id": 182.0,
        "name": "Vincent Villacorta",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/vincentvillacorta.jpg"
    },
    {
        "id": 183.0,
        "name": "Jeffery Wong",
        "class": "Xi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Xi/jefferywong.jpg"
    },
    {
        "id": 184.0,
        "name": "Kulraj Dhaliwal ",
        "class": "Omicron",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/kulrajdhaliwal.jpg"
    },
    {
        "id": 185.0,
        "name": "Lawrence Hwang",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/lawrencehwang.jpg"
    },
    {
        "id": 186.0,
        "name": "Chandan Jain",
        "class": "Omicron",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/chandanjain.jpg"
    },
    {
        "id": 187.0,
        "name": "Christopher La",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/christopherla999/",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/christopherla.jpg"
    },
    {
        "id": 188.0,
        "name": "Angelou Lao",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "linkedin.com/in/angelou-lao/",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Marshal",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/angeloulao.jpg"
    },
    {
        "id": 189.0,
        "name": "Gary Li ",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/garyli.jpg"
    },
    {
        "id": 190.0,
        "name": "Louis Lin ",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "http://linkedin.com/in/louis-lin31",
        "major": "Civil Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Fundraising",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/louislin.jpg"
    },
    {
        "id": 191.0,
        "name": "Vivian Nguyen",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/vivian-truong-nguyen/",
        "major": "Software Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Corresponding Secretary",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/viviannguyen.jpg"
    },
    {
        "id": 192.0,
        "name": "Danny Nguyen",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/dannynguyen.jpg"
    },
    {
        "id": 193.0,
        "name": "Nicholas Silaphet ",
        "class": "Omicron",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Chemical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/nicholassilaphet.jpg"
    },
    {
        "id": 194.0,
        "name": "Tori Spiegel",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "linkedin.com/in/victoriaspiegel",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Vice Regent",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/victoriaspiegel.jpg"
    },
    {
        "id": 195.0,
        "name": "Alexis Vu",
        "class": "Omicron",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/alexisvu.jpg"
    },
    {
        "id": 196.0,
        "name": "Victoria Vuong",
        "class": "Omicron",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/victoriavuong.jpg"
    },
    {
        "id": 197.0,
        "name": "Taekyoo Won ",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/taekyoowon/",
        "major": "Aerospace Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Regent",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/taekyoowon.jpg"
    },
    {
        "id": 198.0,
        "name": "Kelly Wong",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/kelly-briana-wong/",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/kellywong.jpg"
    },
    {
        "id": 199.0,
        "name": "Ryan Zhen",
        "class": "Omicron",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/ryan-zhen/",
        "major": "Civil Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Omicron/ryanzhen.jpg"
    },
    {
        "id": 200.0,
        "name": "Micky Chettanapanich",
        "class": "Pi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/mickychettanapanich.jpg"
    },
    {
        "id": 201.0,
        "name": "Nicholas Chiu ",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/nicholaschiu.jpg"
    },
    {
        "id": 202.0,
        "name": "Yoseph Ghazal ",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "http://linkedin.com/in/yosephghazal",
        "major": "Computer Science",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Brotherhood",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/yosephghazal.jpg"
    },
    {
        "id": 203.0,
        "name": "Justin Ho",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/justin-ho627/",
        "major": "Computer Science",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Media",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/justinho.jpg"
    },
    {
        "id": 204.0,
        "name": "Albert Hong",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "http://linkedin.com/in/albert-hong-bb7825183",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/alberthong.jpg"
    },
    {
        "id": 205.0,
        "name": "Kevin Huynh",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/kevinhuynh.jpg"
    },
    {
        "id": 206.0,
        "name": "Dylan Kao",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "linkedin.com/in/meganlanvynguyen",
        "major": "Electrical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/dylankao.jpg"
    },
    {
        "id": 207.0,
        "name": "Aaron Liang",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "www.linkedin.com/in/aaronhliang",
        "major": "Computer Science",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Website Development",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/aaronliang.jpg"
    },
    {
        "id": 208.0,
        "name": "David Luong",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/davidluong.jpg"
    },
    {
        "id": 209.0,
        "name": "Anderson Nguyen",
        "class": "Pi",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/andersonnguyen.jpg"
    },
    {
        "id": 210.0,
        "name": "Andrew Nguyen",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "Linkedin.com/in/andrewnguyen11",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Public Relations",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/andrewnguyen.jpg"
    },
    {
        "id": 211.0,
        "name": "Lynette Nguyen",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/lynettenguyen14/",
        "major": "Computer Science",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Fundraising",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/lynettenguyen.jpg"
    },
    {
        "id": 213.0,
        "name": "Lily Pham",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/phamlily/",
        "major": "Computer Science",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Treasurer",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/lilypham.jpg"
    },
    {
        "id": 214.0,
        "name": "Cameron Sherry",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/cameronsherry.jpg"
    },
    {
        "id": 216.0,
        "name": "Areeta Wong",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/areeta",
        "major": "Computer Science",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Scribe",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/areetawong.jpg"
    },
    {
        "id": 217.0,
        "name": "Jeffrey Xu ",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/xujeffreyc/",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/jeffreyxu.jpg"
    },
    {
        "id": 218.0,
        "name": "Lauren Yoo",
        "class": "Pi",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/lauren-yoo/",
        "major": "Computer Science",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Recruitment",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Pi/laurenyoo.jpg"
    },
    {
        "id": 219.0,
        "name": "Jonathan Chang",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/changster747",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Engineering",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/jonathanchang.jpg"
    },
    {
        "id": 220.0,
        "name": "Maireen Espiritu",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Software Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Media",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/maireenespiritu.jpg"
    },
    {
        "id": 221.0,
        "name": "Emily Hoang",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/mwlite/in/emilyhhoang",
        "major": "Biomedical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/emilyhoang.jpg"
    },
    {
        "id": 222.0,
        "name": "Eric Hsueh",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/erichsueh3/",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/erichsueh.jpg"
    },
    {
        "id": 223.0,
        "name": "Benjamin Huynh",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/benjaminhuynh.jpg"
    },
    {
        "id": 224.0,
        "name": "Claire Hyon",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Service",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/clairehyon.jpg"
    },
    {
        "id": 225.0,
        "name": "Adrienne Lee",
        "class": "Rho",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Biomedical Engineering & Mechanical Engineering",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/adriennelee.jpg"
    },
    {
        "id": 226.0,
        "name": "Ryan Liao",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "linkedin.com/in/rliao4",
        "major": "Computer Science",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Professional Development",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/ryanliao.jpg"
    },
    {
        "id": 227.0,
        "name": "Lauren Lin",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "NULL",
        "major": "Mechanical Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Brotherhood",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/laurenlin.jpg"
    },
    {
        "id": 228.0,
        "name": "Joshua Liu",
        "class": "Rho",
        "active_status": "Y",
        "linkedin_url": "https://www.linkedin.com/in/joshua-liu/",
        "major": "Computer Science and Engineering",
        "cabby_exec_status": "Y",
        "cabby_exec_position": "Recruitment",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/joshualiu.jpg"
    },
    {
        "id": 229.0,
        "name": "Tam Nguyen",
        "class": "Rho",
        "active_status": "N",
        "linkedin_url": "NULL",
        "major": "Computer Science",
        "cabby_exec_status": "N",
        "profile_url": "https://raw.githubusercontent.com/ttucidev/pi-delta-brothers-images/main/Rho/tamnguyen.jpg"
    }
]